### ISSUE TITLE
1.0 release checklist.

### ISSUE THREAD

**Issue by yunjord** [yunjord/PureZote#12]
- [ ] Resolve as many issues as possible.
- [ ] Skill introduction video both in English and Chinese.
- [ ] Two playthrough videos (attuned and all bindings).
- [ ] Valid channels to receive suggestions.

**Comment by yunjord** [comment]
- [ ] Test the fight in Pantheon 3/5.

**Comment by yunjord** [comment]
Won't do that.
